#!/bin/bash

source scripts/helpers/functions

if [[ ! -f ".checked" ]]; then
  if [[ $DEBIAN_FRONTEND == "noninteractive" ]]; then
    echo "PCKIDRetrievalTool can't be run in non-interactive mode. Please run this script in interactive mode."
    exit 1
  else
    sudo rm -f /tmp/pckid.csv
    sudo PCKIDRetrievalTool -f /tmp/pckid.csv
  fi

  read_intel_api_key

  node ./scripts/helpers/check-fmspc.mjs
  touch .checked
fi
