#!/bin/bash

source .env

block_number=99999

function get_last_block_number() {
  block_number_hex=$(curl "$1" -s -X POST -H "Content-Type: application/json" --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}' | jq -r ".result")
  block_number=$((block_number_hex))
}

if [ -z "$SRN_NETWORK" ]; then
  read -r -e -p "Chain [taiko_mainnet, taiko_a7]: " -i "${CHAIN:-taiko_a7}" SRN_NETWORK
fi

if [ "$SRN_NETWORK" == "taiko_a7" ]; then
  if [ -z "$SRN_TAIKO_A7_RPC" ]; then
    read -r -e -p "Specify the Taiko A7 RPC endpoint: " SRN_TAIKO_A7_RPC
  fi
  get_last_block_number "${SRN_TAIKO_A7_RPC}"
elif [ "$SRN_NETWORK" == "taiko_mainnet" ]; then
  if [ -z "$SRN_TAIKO_MAINNET_RPC" ]; then
    read -r -e -p "Specify the Taiko Mainnet RPC endpoint: " SRN_TAIKO_MAINNET_RPC
  fi
  get_last_block_number "${SRN_TAIKO_MAINNET_RPC}"
fi

read -r -e -p "Proof type [native, sp1, sgx, risc0, risc0-bonsai]: " -i "${PROOF_TYPE:-sgx}" PROOF_TYPE
read -r -e -p "Block number: " -i "${RANGE_START:-${block_number}}" RANGE_START

source ./scripts/override/prove-block.sh "${SRN_NETWORK}" "${PROOF_TYPE}" "${RANGE_START}"
